### PR TITLE
Fix SLICE_TOO_SMALL error

### PR DESCRIPTION
**Pull request by ericthewry**
I had to close the previous pull request; the rebasing screwed things up somehow. 

@ahorn

### CODE REVIEW

**Comment by ahorn** [comment]
@ericthewry The build failed.

**Comment by ericthewry** [comment]
@ahorn Whoops! I forgot that `make run-test` doesn't also run `make` 💥 .  Fixed now!

**Comment by ahorn** [comment]
@ericthewry Thank you for putting this patch together. I have proposed a fix in commit 11b67292e9eca88821eb3a9f5bbca8e1d877bf64. Please have a look and let me know what you think.

**Comment by ahorn** [comment]
Out of date, new fix using a simpler approach instead. Closing.

**Pull request closed without merging**
